version: 2.1

orbs:
  node: circleci/node@5.0.1

build:
  docker:
    - image: cimg/node:16.10
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run: |
        echo "Installing dependencies..."
        npm install

test:
  docker:
    - image: cimg/node:16.10
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run: |
        echo "Running tests..."
        npm run test

publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: DOCKERHUB_PASSWORD  # DOCKER_PASSWORD is the default value
      - docker/build:
          image: mohdfirhat/test_repository
      - docker/push:
          image: mohdfirhat/test_repository

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
        requires:
          - build
      - publish:
        requires:
          - build
          - test